export const buyers = {
  1: {
    id: "1",
    name: "Ethan Anderson",
    address: "",
    phone: "",
    email: "",
    account_balance: 20000,
    bought_products: ["3", "6"],
    current_biddings: ["1", "2", "3"],
    image: "/profile_pics/buyer1.jpg",
    biography: "",
  },
  2: {
    id: "2",
    name: "Jacob Matthews",
    address: "",
    phone: "",
    email: "",
    account_balance: 20000,
    bought_products: ["3", "6"],
    current_biddings: ["5", "6"],
    image: "/profile_pics/buyer2.jpg",
    biography: "",
  },
  3: {
    id: "3",
    name: "Emma Wilson",
    address: "",
    phone: "",
    email: "",
    account_balance: 20000,
    bought_products: ["3", "6"],
    current_biddings: ["4"],
    image: "/profile_pics/buyer3.jpg",
    biography: "",
  },
  4: {
    id: "4",
    name: "William Parker",
    address: "",
    phone: "",
    email: "",
    account_balance: 20000,
    bought_products: ["3", "6"],
    current_biddings: [],
    image: "/profile_pics/buyer4.jpg",
    biography: "",
  },
};
