export const products = {
  1: {
    id: "1",
    name: "Victorian Sofa",
    minimum_bid_price: 5000,
    current_bid_price: 6000,
    bid_complete_date: "",
    seller_id: "2",
    buyer_id: "1",
    status: "unsold",
    categories: ["1"],
    image: "/products/prod1.jpeg",
    description: "",
  },
  2: {
    id: "2",
    name: "Sheraton Table",
    minimum_bid_price: 4000,
    current_bid_price: 7000,
    bid_complete_date: "",
    seller_id: "4",
    buyer_id: "1",
    status: "unsold",
    categories: ["1"],
    image: "/products/prod2.jpeg",
    description: "",
  },
  3: {
    id: "3",
    name: "Venus de Milo",
    minimum_bid_price: 3500,
    current_bid_price: 6000,
    bid_complete_date: "",
    seller_id: "1",
    buyer_id: "1",
    status: "unsold",
    categories: ["2"],
    image: "/products/prod3.webp",
    description: "",
  },
  4: {
    id: "4",
    name: "Mercator Globe",
    minimum_bid_price: 7000,
    current_bid_price: 8000,
    bid_complete_date: "",
    seller_id: "3",
    buyer_id: "3",
    status: "unsold",
    categories: ["3"],
    image: "/products/prod4.webp",
    description: "",
  },
  5: {
    id: "5",
    name: "Crown of Saint Wenceslas",
    minimum_bid_price: 6500,
    current_bid_price: 10000,
    bid_complete_date: "",
    seller_id: "4",
    buyer_id: "2",
    status: "unsold",
    categories: ["4"],
    image: "/products/prod5.jpeg",
    description: "",
  },
  6: {
    id: "6",
    name: "Waterman Ideal",
    minimum_bid_price: 2500,
    current_bid_price: 3700,
    bid_complete_date: "",
    seller_id: "1",
    buyer_id: "2",
    status: "unsold",
    categories: ["5"],
    image: "/products/prod6.jpeg",
    description: "",
  },
};
