export const sellers = {
  1: {
    id: "1",
    name: "Michael Davis",
    address: "United Nations",
    phone: "",
    email: "",
    account_balance: 20000,
    listings: ["3", "6"],
    image: "/profile_pics/seller1.png",
    biography: "",
  },
  2: {
    id: "2",
    name: "Emily Johnson",
    address: "London",
    phone: "",
    email: "",
    account_balance: 20000,
    listings: ["1"],
    image: "/profile_pics/seller2.png",
    biography: "",
  },
  3: {
    id: "3",
    name: "Sarah Wilson",
    address: "Mumbai",
    phone: "",
    email: "",
    account_balance: 20000,
    listings: ["4"],
    image: "/profile_pics/seller3.png",
    biography: "",
  },
  4: {
    id: "4",
    name: "Jessica Brown",
    address: "Karnataka",
    phone: "",
    email: "",
    account_balance: 20000,
    listings: ["2", "5"],
    image: "/profile_pics/seller4.png",
    biography: "",
  },
};
